### PR TITLE
Merge veepee work to main

### PR DESCRIPTION
**Pull request by vaxvms**
This PR merge work from #21 into main branch

### CODE REVIEW

**Comment by vaxvms** [comment]
Hi,

Is there something wrong with this PR ?

**Comment by yzhivkov** [comment]
When can we expect this PR to be merged and released? We would like to be able to use the awx_user functionality asap

**Review by denouche — APPROVED** [review]

**Comment by denouche** [comment]
Hello, I'm really sorry for a so long delay in my answers.
Now I take a look to the opened PR and I wanted to merge this one but their are some conflicts, can you rebase it please?

**Comment by vaxvms** [comment]
Great to hear ! I have some more PR to submit, i'll prepare them tomorrow afternoon

Should be ok to merge

**Review by denouche — APPROVED** [review]

**Pull request merged**
